### ISSUE TITLE
unable to start a WebDriver session

### ISSUE THREAD

**Issue by colorpeach** [angular/angular-seed#251]
when I exec 'npm run protractor', I got 'unable to start a WebDriver session'.

Error is below:
```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
ERROR - Unable to start a WebDriver session.

d:\xinliangwang\repo\angular-seed\node_modules\protractor\node_modules\selenium-
webdriver\http\index.js:145
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (d:\xinliangwang\repo\angular-seed\node_modules
\protractor\node_modules\selenium-webdriver\http\index.js:145:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1552:9)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (d:\xinliangwang\repo\angula
r-seed\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\web
driver.js:149:22)
    at Function.webdriver.WebDriver.createSession (d:\xinliangwang\repo\angular-
seed\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdr
iver.js:123:30)
    at Builder.build (d:\xinliangwang\repo\angular-seed\node_modules\protractor\
node_modules\selenium-webdriver\builder.js:294:22)
    at DriverProvider.getNewDriver (d:\xinliangwang\repo\angular-seed\node_modul
es\protractor\lib\driverProviders\driverProvider.js:50:7)
    at Runner.createBrowser (d:\xinliangwang\repo\angular-seed\node_modules\prot
ractor\lib\runner.js:178:37)
    at d:\xinliangwang\repo\angular-seed\node_modules\protractor\lib\runner.js:2
59:24
    at _fulfilled (d:\xinliangwang\repo\angular-seed\node_modules\protractor\nod
e_modules\q\q.js:797:54)
    at self.promiseDispatch.done (d:\xinliangwang\repo\angular-seed\node_modules
\protractor\node_modules\q\q.js:826:30)
    at Promise.promise.promiseDispatch (d:\xinliangwang\repo\angular-seed\node_m
odules\protractor\node_modules\q\q.js:759:13)
[launcher] Process exited with error code 1
```

Config is below:
```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  
  allScriptsTimeout: 11000,

  specs: [
    '*.js'
  ],

  capabilities: {
    'browserName': 'chrome'
  },

  baseUrl: 'http://localhost:8000/app/',

  framework: 'jasmine',

  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }
};

```

**Comment by NilapuAnusha** [comment]
@iamisti i ran 'webdriver-manager start' command on command prompt but it didn't fix my issue? Could you please take a look on http://stackoverflow.com/questions/29294282/protractor-error-unable-to-start-a-webdriver-session

**Comment by iamisti** [comment]
@NilapuAnusha I'm sure you didn't start 'webdriver-manager' or at least you close it before you run your tests.

Make sure you open it in an other command prompt, and when it runs, run your selenium tests and it should work.

**Comment by anilapu** [comment]
@iamisti Yes. That is true. When i start protractor test case running before that i need to run webdriver-manager parallel in other command prompt but my doubt is previously i didn't ran webdriver-manager start parallel to protractor. I just started webdriver-manager after that i stopped. Every time i didn't that webdriver-manager only once first time installation

**Comment by josefsalyer** [comment]
replace:
````
seleniumAddress: 'http://localhost:4444/wd/hub'
````

with: 
````
seleniumServerJar: '../node_modules/protractor/selenium/selenium-server-standalone-2.45.0.jar'
````

This solves the problem by launching the selenium standalone server jar directly.
