### ISSUE TITLE
Error in e2e tests with protractor

### ISSUE THREAD

**Issue by lasanthab** [angular/angular-seed#256]
I found an issue in protractor configuration file. It should contain a line like,

"seleniumAddress": 'http://localhost:4444/wd/hub',

to work properly. And before you run the test, you should start webdriver using command,

webdriver-manager start

**Comment by micahblu** [comment]
I've included that line and ran `webdriver-manager start` before running in a separate terminal `protractor e2e-tests/protractor.conf.js` and protractor still does not work, I get the following errors:

```shell
MacBook:angular-seed micahblu$ protractor e2e-tests/protractor.conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
FF
/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877
      var result = fn();
                   ^
Error: Angular could not be found on the page http://localhost:8000/app/index.html : retries looking for angular exceeded
    at /usr/local/lib/node_modules/protractor/lib/protractor.js:479:17
    at [object Object].promise.ControlFlow.runInFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
    at [object Object].promise.Callback_.goog.defineClass.notify (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
    at [object Object].promise.Promise.notify_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)
    at Array.forEach (native)
    at Object.goog.array.forEach (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)
    at [object Object].promise.Promise.notifyAll_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)
    at [object Object].goog.async.run.processWorkQueue [as _onTimeout] (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(11000)
    at [object Object].webdriver.WebDriver.schedule (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:360:15)
    at [object Object].webdriver.WebDriver.Timeouts.setScriptTimeout (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1367:23)
    at [object Object].Runner.createBrowser (/usr/local/lib/node_modules/protractor/lib/runner.js:181:30)
    at /usr/local/lib/node_modules/protractor/lib/runner.js:257:21
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:573:44
    at flush (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
[launcher] Process exited with error code 1
```
I think it may have something to do with the baseUrl option, as it does pull up a browser window with that url however it provides a "webpage is unavailable" message in the blank window. That would explain why it can't find angular.

**Comment by gkalpak** [comment]
All dependencies and tools have been updated recently and this is hopefully no problem any more.
Please open a new issue, if you are still facing problems.
