### ISSUE TITLE
Testing: 'descripe' is not defined (with karma and protractor)

### ISSUE THREAD

**Issue by TBoonX** [angular/angular-seed#301]
With protractor or karma 'descripe' of jasmine is not defined.
I cleaned all of bower, npm and node.js and reinstalled it. I just used this project with 'npm install'.
If I call protractor directly, the same error occurs.
jasmine is installed in the directory node_modules.
I tried to include jasmine-core.js in protractor.conf.js.
protractor uses the correct config file.

Please help me with this. I really want to write tests!

npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-seed@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-seed@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-seed@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:818:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid angular-seed@0.0.0
12 verbose cwd c:\Entwicklung\AgriConnect\Test\angularseed
13 error Windows_NT 6.1.7601
14 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
15 error node v4.2.1
16 error npm  v2.14.7
17 error code ELIFECYCLE
18 error angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 error Exit status 1
19 error Failed at the angular-seed@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
19 error This is most likely a problem with the angular-seed package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor e2e-tests/protractor.conf.js
19 error You can get their info via:
19 error     npm owner ls angular-seed
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

Console output:
$ npm run protractor
> angular-seed@0.0.0 preprotractor c:\Entwicklung\AgriConnect\Test\angularseed
> npm run update-webdriver
> angular-seed@0.0.0 preupdate-webdriver c:\Entwicklung\AgriConnect\Test\angular
seed
> npm install
> angular-seed@0.0.0 postinstall c:\Blub\angularseed
> bower install
> angular-seed@0.0.0 update-webdriver c:\Blub\angularsee
d
> webdriver-manager update
selenium standalone is up to date.
chromedriver is up to date.
> angular-seed@0.0.0 protractor c:\Blub\angularseed
> protractor e2e-tests/protractor.conf.js
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.99.101:61730/wd/hub
F

Failures:
  1) Exception loading: c:\Blub\angularseed\e2e-tests\te
stCtrlTasklist.js Error
   Message:
     ReferenceError: descripe is not defined
   Stacktrace:
     ReferenceError: descripe is not defined
    at Object.<anonymous> (c:\Blub\angularseed\e2e-tests
\testCtrlTasklist.js:1:63)
    at require (module.js:385:17)
    at Object.exports.executeSpecs (c:\Blub\angularseed\
node_modules\protractor\node_modules\minijasminenode\lib\index.js:130:7)
    at c:\Blub\angularseed\node_modules\protractor\lib\f
rameworks\jasmine.js:88:14
    at Function.promise (c:\Blub\angularseed\node_module
s\protractor\node_modules\q\q.js:650:9)

Finished in 0.017 seconds
1 test, 1 assertion, 1 failure

Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 protractor script 'protractor e2e-test
s/protractor.conf.js'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Blub\angularseed\npm-debug.log

**Comment by TBoonX** [comment]
I misspelled the method ...
Sorry for distraction.
