### ISSUE TITLE
npm run protractor failed

### ISSUE THREAD

**Issue by sekitaka** [angular/angular-seed#302]
Hello ,
I am learning AngularJS Phonecap tutorial.
When I run "npm run protractor" , following error has occured.
Do you have any idea ? 
Mac OSX, Node v4.2.1, npm v2.14.7.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-seed@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-seed@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-seed@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:818:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid angular-seed@0.0.0
12 verbose cwd /Users/sekitakashi/PhpstormProjects/AngularJS_tutorial
13 error Darwin 14.5.0
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
15 error node v4.2.1
16 error npm  v2.14.7
17 error code ELIFECYCLE
18 error angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 error Exit status 1
19 error Failed at the angular-seed@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
19 error This is most likely a problem with the angular-seed package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor e2e-tests/protractor.conf.js
19 error You can get their info via:
19 error     npm owner ls angular-seed
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

Thank you.

**Comment by sekitaka** [comment]
I changed to NodeJS 0.12.7 and run `sudo npm run protractor`, then It worked.
