### ISSUE TITLE
Error when running conf.js file - Protractor

### ISSUE THREAD

**Issue by tomerqa** [angular/angular-seed#318]
Hello,
I installed Protractor on my Linux environment.

Nodejs: 
v0.12.9

npm: 
2.14.9

I started up the web server, and it's looking good:
java -jar /usr/lib/node_modules/protractor/selenium/selenium-server-standalone-2.48.2.jar -Dwebdriver.chrome.driver=/usr/lib/node_modules/protractor/selenium/chromedriver

But, when i run the "conf.js" file, as told me in the buttom of the potractor website: http://angular.github.io/protractor/#/ , 

I got the following error:

[launcher] Process exited with error code 1
undefined:1190
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Object.Context.closure.goog.retrieveAndExecModule_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:900:14)

Somebody can please help me with that ?

Thank you!

**Comment by gkalpak** [comment]
You should not follow the generic instructions on the Protractor docs, since they assume a slightly different setup. For this project, you can use `npm run protractor` (after having started a server with `npm start` in a different terminal). See [here][1] for more info.

Closing, but feel free to reopen if this doesn't solve your problem.

[1]: https://github.com/angular/angular-seed#end-to-end-testing
