### ISSUE TITLE
Npm install and npm start issue in a clean cloned repo

### ISSUE THREAD

**Issue by JhonyVidal** [angular/angular-seed#377]
Hi guys, I've just cloned angular-seed repo into my frontend folder in my project and when I tried to install **sudo npm install** It gives me the following error: 

`npm WARN lifecycle angular2-seed@0.0.0~postinstall: cannot run in wd %s %s (wd=%s) angular2-seed@0.0.0 gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner /var/www/html/active_projects/my_project_root/frontend`

and when I run **sudo npm start**:

`[17:51:35] Using gulpfile /var/www/html/active_projects/my_project_root/frontend/gulpfile.ts
[17:51:35] Starting 'serve.dev'...
[17:51:35] Starting 'build.dev'...
[17:51:35] Starting 'build.assets.dev'...
[17:51:35] Finished 'build.assets.dev' after 395 ms
[17:51:35] Starting 'build.html_css'...
[17:51:43] 'build.html_css' errored after 7.1 s
[17:51:43] Error: Cannot find module '.tmp/Rx.min.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at /var/www/html/active_projects/my_project_root/frontend/tools/config/seed.config.ts:582:59
    at Array.forEach (native)
    at normalizeDependencies (/var/www/html/active_projects/my_project_root/frontend/tools/config/seed.config.ts:582:6)
    at ProjectConfig.get [as DEPENDENCIES] (/var/www/html/active_projects/my_project_root/frontend/tools/config/seed.config.ts:335:12)
    at getExternalCss (/var/www/html/active_projects/my_project_root/frontend/tools/tasks/seed/build.html_css.ts:112:16)
    at getExternalCssStream (/var/www/html/active_projects/my_project_root/frontend/tools/tasks/seed/build.html_css.ts:104:19)
    at processExternalCss (/var/www/html/active_projects/my_project_root/frontend/tools/tasks/seed/build.html_css.ts:138:10)
    at processExternalStylesheets (/var/www/html/active_projects/my_project_root/frontend/tools/tasks/seed/build.html_css.ts:85:65)
[17:51:43] 'serve.dev' errored after 7.61 s
[17:51:43] Error in plugin 'run-sequence(build.html_css)'
Message:
    Cannot find module '.tmp/Rx.min.js'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module '.tmp/Rx.min.js'
`

Is this something related to npm/gulp/bower or angular-seed, initially I thought it was something related uniquelly to this: **tmp/this Rx.min.js ** **frontend/tools/config/seed.config.ts:582:59**

I've tried, **npm run reinstall**, **npm cache clean && npm install** and after read [#1451](https://github.com/mgechev/angular-seed/issues/1451)  **tsc** in my angular-seed root folder(frontend) but I don't think that is really necessary as I'm in unix environment, so I just let the gulpfile.ts not the one in .js or .js.map, are thouse files necessary(gulpfile.js and gulpfile.js.map), curiosity? 

Another issue related:[#1298]( https://github.com/mgechev/angular-seed/issues/1298) which I tested and had no conflicts with **npm run build.prod**.

I still couldn't find a solution to it, same error, any idea of what can be?  Thanx a lot!

**Comment by JhonyVidal** [comment]
I could **run start** correctly by doing manually **sudo gulp build.bundle.rxjs** , before I installed rxjs library *sudo npm install rxjs* but I'm not sure if it was needed or not.  

However it's still return the same error on *npm install*, there is certaintly some conflict in that section. I'll be digging on it to figure out what may be causing this error.

I'm not sure if is something related to this issue [issue#9359](https://github.com/angular/angular/issues/9359 ) and pull request(files to be looked) [pull#1390](https://github.com/mgechev/angular-seed/pull/1390/files). 

I'm quite newbie to all these frontend-development/automated tools stuff and GitHub Community collaboration(still poor in public repositories but I'm working on it!! followers... better not talking) but I'm really keen on participating @mgechev more and more from now on, just loved Angular1 and now Angular2 and with angular-seed the sky is the limit :-)

**Comment by mgechev** [comment]
@JhonyVidal would you remove `gulp build.bundle.rxjs` from `postinstall` and remove [this line from your config](https://github.com/mgechev/angular-seed/pull/1390/files#diff-3d695f3c2a28f15f1129d3a122b806d5R282). Do you still get the error?

**Comment by mgechev** [comment]
Hey @JhonyVidal, I'm afraid you've opened this issue in the wrong repository. Probably you mean [this one](https://github.com/mgechev/angular-seed).

Once we move the discussion to [here](https://github.com/mgechev/angular-seed), please also follow up with the result of `npm i` after you drop `gulp build.bundle.rxjs` from `postinstall` and removal [of this line](https://github.com/mgechev/angular-seed/pull/1390/files#diff-3d695f3c2a28f15f1129d3a122b806d5R282).

**Comment by JhonyVidal** [comment]
This issue was moved to mgechev/angular-seed#1496
