### ISSUE TITLE
npm install problem with the last version (node and npm)

### ISSUE THREAD

**Issue by rubenns** [angular/angular-seed#396]
I have tried to do npm install with node v6.9.5 and v3.10.10 and the error is the next one:

[21:15:12] Requiring external module ts-node/register
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at load (/Users/Ruben/development/angular-seed/node_modules/ts-node/src/index.ts:191:27)
    at service (/Users/Ruben/development/angular-seed/node_modules/ts-node/src/index.ts:370:32)
    at Module.m._compile (/Users/Ruben/development/angular-seed/node_modules/ts-node/src/index.ts:413:34)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/Ruben/development/angular-seed/node_modules/ts-node/src/index.ts:416:12)
    at Module.load (module.js:487:32)

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/Ruben/development/tools/node-v6.9.5/bin/node" "/Users/Ruben/development/tools/node-v6.9.5/lib/node_modules/npm/bin/npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 postinstall: `gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner`
npm ERR! Exit status 1

**Comment by rubenns** [comment]
Sorry, it's fixed with cache clean, remove node-modules and install again... it should be a local machine problem.
