### ISSUE TITLE
npm run update-webdriver failed 

### ISSUE THREAD

**Issue by Sunny-Kid** [angular/angular-seed#405]
```
0 info it worked if it ends with ok
1 verbose cli [ 'G:\\NodeJS\\node.exe',
1 verbose cli   'G:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'update-webdriver' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'preupdate-webdriver',
4 verbose run-script   'update-webdriver',
4 verbose run-script   'postupdate-webdriver' ]
5 info lifecycle angular-seed@0.0.0~preupdate-webdriver: angular-seed@0.0.0
6 verbose lifecycle angular-seed@0.0.0~preupdate-webdriver: unsafe-perm in lifecycle true
7 verbose lifecycle angular-seed@0.0.0~preupdate-webdriver: PATH: G:\NodeJS\node_modules\npm\bin\node-gyp-bin;F:\workSpace\angular-seed\node_modules\.bin;C:\Users\平常\bin;G:\Git\mingw64\bin;G:\Git\usr\local\bin;G:\Git\usr\bin;G:\Git\usr\bin;G:\Git\mingw64\bin;G:\Git\usr\bin;C:\Users\平常\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;G:\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;G:\NodeJS;F:\Ruby23-x64\bin;C:\Users\平常\AppData\Local\Microsoft\WindowsApps;C:\Users\平常\AppData\Roaming\npm;G:\Git\usr\bin\vendor_perl;G:\Git\usr\bin\core_perl
8 verbose lifecycle angular-seed@0.0.0~preupdate-webdriver: CWD: F:\workSpace\angular-seed
9 silly lifecycle angular-seed@0.0.0~preupdate-webdriver: Args: [ '/d /s /c', 'npm install' ]
10 silly lifecycle angular-seed@0.0.0~preupdate-webdriver: Returned: code: 0  signal: null
11 info lifecycle angular-seed@0.0.0~update-webdriver: angular-seed@0.0.0
12 verbose lifecycle angular-seed@0.0.0~update-webdriver: unsafe-perm in lifecycle true
13 verbose lifecycle angular-seed@0.0.0~update-webdriver: PATH: G:\NodeJS\node_modules\npm\bin\node-gyp-bin;F:\workSpace\angular-seed\node_modules\.bin;C:\Users\平常\bin;G:\Git\mingw64\bin;G:\Git\usr\local\bin;G:\Git\usr\bin;G:\Git\usr\bin;G:\Git\mingw64\bin;G:\Git\usr\bin;C:\Users\平常\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;G:\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;G:\NodeJS;F:\Ruby23-x64\bin;C:\Users\平常\AppData\Local\Microsoft\WindowsApps;C:\Users\平常\AppData\Roaming\npm;G:\Git\usr\bin\vendor_perl;G:\Git\usr\bin\core_perl
14 verbose lifecycle angular-seed@0.0.0~update-webdriver: CWD: F:\workSpace\angular-seed
15 silly lifecycle angular-seed@0.0.0~update-webdriver: Args: [ '/d /s /c', 'webdriver-manager update' ]
16 silly lifecycle angular-seed@0.0.0~update-webdriver: Returned: code: 1  signal: null
17 info lifecycle angular-seed@0.0.0~update-webdriver: Failed to exec update-webdriver script
18 verbose stack Error: angular-seed@0.0.0 update-webdriver: `webdriver-manager update`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (G:\NodeJS\node_modules\npm\lib\utils\lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (G:\NodeJS\node_modules\npm\lib\utils\spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:877:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-seed@0.0.0
20 verbose cwd F:\workSpace\angular-seed
21 error Windows_NT 10.0.14393
22 error argv "G:\\NodeJS\\node.exe" "G:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "update-webdriver"
23 error node v6.10.0
24 error npm  v3.10.10
25 error code ELIFECYCLE
26 error angular-seed@0.0.0 update-webdriver: `webdriver-manager update`
26 error Exit status 1
27 error Failed at the angular-seed@0.0.0 update-webdriver script 'webdriver-manager update'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-seed package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     webdriver-manager update
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-seed
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-seed
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Comment by Sunny-Kid** [comment]
I have runed npm start before , but it seems when I run npm run protractor ,it doesn't work

**Comment by gkalpak** [comment]
There is not enough info to investigate this. For some reason, it seems that `npm update-webdriver` fails.
What is the output of `node_modules/.bin/webdriver-manager update` (from within the project directory)?

**Comment by Sunny-Kid** [comment]
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../protractor/bin/webdriver-manager" "$@"
  ret=$?
else 
  node  "$basedir/../protractor/bin/webdriver-manager" "$@"
  ret=$?
fi
exit $ret
```

**Comment by Sunny-Kid** [comment]
Thank you for your reply , the content of >node_modules/.bin/webdriver-manager update is as bellow:
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../protractor/bin/webdriver-manager" "$@"
  ret=$?
else 
  node  "$basedir/../protractor/bin/webdriver-manager" "$@"
  ret=$?
fi
exit $ret
```

**Comment by gkalpak** [comment]
I meant what is the output of running the command `node_modules/.bin/webdriver-manager update` in your terminal (from within the project root).

**Comment by Sunny-Kid** [comment]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 74.125.23.128:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

**Comment by gkalpak** [comment]
Is there any firewall that is blocking your network traffic?

**Comment by Sunny-Kid** [comment]
No,but today , I try again ,  it works ,I dont't know the reason

**Comment by gkalpak** [comment]
The important thing is that it works :smiley:
Glad you were able to sort it out!

**Comment by walkerrandolphsmith** [comment]
This happens intermittently for us. What information would be helpful to troubleshoot the issue?
