### ISSUE TITLE
Angular Seed Stopped Working. Error Code Below

### ISSUE THREAD

**Issue by paultofunmi** [angular/angular-seed#417]
Hi, I am fairly new to angular. I experienced this bug. Even after changing the port, the error still persists. Any help?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.0.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.0.1
3 info using node@v8.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-seed@0.0.0~prestart: angular-seed@0.0.0
6 verbose lifecycle angular-seed@0.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle angular-seed@0.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/paultofunmi/Sites/TrainingProjects/10ProjectsInAngularTutorialUdemy/TemplateStore/node_modules/.bin:/Users/paultofunmi/.composer/vendor/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
8 verbose lifecycle angular-seed@0.0.0~prestart: CWD: /Users/paultofunmi/Sites/TrainingProjects/10ProjectsInAngularTutorialUdemy/TemplateStore
9 silly lifecycle angular-seed@0.0.0~prestart: Args: [ '-c', 'npm install' ]
10 silly lifecycle angular-seed@0.0.0~prestart: Returned: code: 0  signal: null
11 info lifecycle angular-seed@0.0.0~start: angular-seed@0.0.0
12 verbose lifecycle angular-seed@0.0.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle angular-seed@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/paultofunmi/Sites/TrainingProjects/10ProjectsInAngularTutorialUdemy/TemplateStore/node_modules/.bin:/Users/paultofunmi/.composer/vendor/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
14 verbose lifecycle angular-seed@0.0.0~start: CWD: /Users/paultofunmi/Sites/TrainingProjects/10ProjectsInAngularTutorialUdemy/TemplateStore
15 silly lifecycle angular-seed@0.0.0~start: Args: [ '-c', 'http-server -a localhost -p 81000 -c-1 ./app' ]
16 silly lifecycle angular-seed@0.0.0~start: Returned: code: 1  signal: null
17 info lifecycle angular-seed@0.0.0~start: Failed to exec start script
18 verbose stack Error: angular-seed@0.0.0 start: `http-server -a localhost -p 81000 -c-1 ./app`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at EventEmitter.emit (events.js:213:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at ChildProcess.emit (events.js:213:7)
18 verbose stack     at maybeClose (internal/child_process.js:887:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
19 verbose pkgid angular-seed@0.0.0
20 verbose cwd /Users/paultofunmi/Sites/TrainingProjects/10ProjectsInAngularTutorialUdemy/TemplateStore
21 verbose Darwin 16.5.0
22 verbose argv "/usr/local/Cellar/node/8.0.0_1/bin/node" "/usr/local/bin/npm" "start"
23 verbose node v8.0.0
24 verbose npm  v5.0.1
25 error code ELIFECYCLE
26 error errno 1
27 error angular-seed@0.0.0 start: `http-server -a localhost -p 8000 -c-1 ./app`
27 error Exit status 1
28 error Failed at the angular-seed@0.0.0 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by paultofunmi** [comment]
Fixed now. I changed the port to a different port
