### ISSUE TITLE
Error npm run protractor

### ISSUE THREAD

**Issue by dspizzirri-ge** [angular/angular-seed#461]
I need to help for this issue. 
I don't understand why it doesn't work

```
npm run protractor

> angular-seed@0.0.0 preprotractor C:\Users\Voldemort\Documents\Laboratorio\angular-seed
> npm run update-webdriver


> angular-seed@0.0.0 preupdate-webdriver C:\Users\Voldemort\Documents\Laboratorio\angular-seed       
> npm install


> angular-seed@0.0.0 postinstall C:\Users\Voldemort\Documents\Laboratorio\angular-seed
> npm run copy-libs


> angular-seed@0.0.0 copy-libs C:\Users\Voldemort\Documents\Laboratorio\angular-seed
> cpx "node_modules/{angular,angular-*,html5-boilerplate/dist}/**/*" app/lib -C

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 3902 packages in 6.551s

3 packages are looking for funding
  run `npm fund` for details

found 6 vulnerabilities (5 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> angular-seed@0.0.0 update-webdriver C:\Users\Voldemort\Documents\Laboratorio\angular-seed
> webdriver-manager update --gecko false

[18:56:54] I/config_source - curl -oC:\Users\Voldemort\Documents\Laboratorio\angular-seed\node_modules\protractor\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
[18:56:54] I/config_source - curl -oC:\Users\Voldemort\Documents\Laboratorio\angular-seed\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[18:56:56] I/update - selenium standalone: file exists C:\Users\Voldemort\Documents\Laboratorio\angular-seed\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.141.59.jar
[18:56:56] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date        
[18:56:56] I/update - chromedriver: file exists C:\Users\Voldemort\Documents\Laboratorio\angular-seed\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_81.0.4044.69.zip       
[18:56:56] I/update - chromedriver: unzipping chromedriver_81.0.4044.69.zip
[18:56:56] I/update - chromedriver: chromedriver_81.0.4044.69.exe up to date

> angular-seed@0.0.0 protractor C:\Users\Voldemort\Documents\Laboratorio\angular-seed
> protractor e2e-tests/protractor.conf.js

[18:56:57] I/launcher - Running 1 instances of WebDriver
[18:56:57] I/local - Starting selenium standalone server...
[18:56:57] E/launcher - spawn C:\Program Files\Java\jdk1.8.0_251\bin\bin\java ENOENT
[18:56:57] E/launcher - Error: spawn C:\Program Files\Java\jdk1.8.0_251\bin\bin\java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[18:56:57] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 199
npm ERR! angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 199
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 protractor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.   

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Voldemort\AppData\Roaming\npm-cache\_logs\2020-05-01T21_56_57_477Z-debug.log   
```

**Comment by dspizzirri-ge** [comment]
I have already solve the issue. My JAVA_HOME variable was wrong.
