### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by Pr0methean** [angular/angular-seed#462]
I get this error creating a new project (which is initially a copy of angular-seed) in WebStorm.
[npm-debug.log](https://github.com/angular/angular-seed/files/4802083/npm-debug.log)

```
> http-server -a localhost -p 8000 -c-1 ./app


/home/chris/git/SiteF1/node_modules/http-server/node_modules/ecstatic/lib/ecstatic.js:5
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/chris/git/SiteF1/node_modules/http-server/lib/http-server.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 5.4.0-37-generic
npm ERR! argv "/home/chris/.nvm/v0.10.48/bin/node" "/home/chris/.nvm/v0.10.48/bin/npm" "start"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 start: `http-server -a localhost -p 8000 -c-1 ./app`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 start script 'http-server -a localhost -p 8000 -c-1 ./app'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a localhost -p 8000 -c-1 ./app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chris/git/SiteF1/npm-debug.log
```

**Comment by Pr0methean** [comment]
[npm-debug.log](https://github.com/angular/angular-seed/files/4802085/npm-debug.log)

**Comment by gkalpak** [comment]
This error comes from 3rd-party packages (more specifically `ecstatic` which is a dependency of `http-server`). You seem to be using a very old version of Node.js (0.10.48). Try updating your Node.js to the latest stable version (or at least a reasonably recent version :grin:).
