### ISSUE TITLE
Issue with npm run protractor

### ISSUE THREAD

**Issue by PraneetDixit** [angular/angular-seed#466]
I am trying to use `protractor` to perform e2e tests on my project. When I run `npm run protractor`, I get the following errors -

![Error img 1](https://raw.githubusercontent.com/PraneetDixit/Assets/main/npme1.JPG)<br>
![Error img 2](https://raw.githubusercontent.com/PraneetDixit/Assets/main/npme2.JPG)<br>
![Error img 3](https://raw.githubusercontent.com/PraneetDixit/Assets/main/npme3.JPG)<br>

The error logfile is as below - 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\admin pc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-seed@0.0.0~preprotractor: angular-seed@0.0.0
6 verbose lifecycle angular-seed@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-seed@0.0.0~preprotractor: PATH: C:\Users\admin pc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\admin pc\WebstormProjects\Blog\node_modules\.bin;C:\Users\admin pc\WebstormProjects\Blog\node_modules\.bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;E:\MinG\Bin;C:\Program Files\Brackets\command;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\admin pc\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\admin pc\AppData\Local\Programs\Python\Python36-32\;C:\Users\admin pc\AppData\Local\Programs\Microsoft VS Code\bin;E:\MinG\Bin;E:\dart-sass;C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.1\bin;;C:\Program Files\JetBrains\WebStorm 2019.3.5\bin;;C:\Users\admin pc\AppData\Roaming\npm
8 verbose lifecycle angular-seed@0.0.0~preprotractor: CWD: C:\Users\admin pc\WebstormProjects\Blog
9 silly lifecycle angular-seed@0.0.0~preprotractor: Args: [ '/d /s /c', 'npm run update-webdriver' ]
10 silly lifecycle angular-seed@0.0.0~preprotractor: Returned: code: 1  signal: null
11 info lifecycle angular-seed@0.0.0~preprotractor: Failed to exec preprotractor script
12 verbose stack Error: angular-seed@0.0.0 preprotractor: `npm run update-webdriver`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Users\admin pc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:315:20)
12 verbose stack     at ChildProcess.<anonymous> (C:\Users\admin pc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1048:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
13 verbose pkgid angular-seed@0.0.0
14 verbose cwd C:\Users\admin pc\WebstormProjects\Blog
15 verbose Windows_NT 6.3.9600
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin pc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
17 verbose node v14.15.0
18 verbose npm  v6.14.8
19 error code ELIFECYCLE
20 error errno 1
21 error angular-seed@0.0.0 preprotractor: `npm run update-webdriver`
21 error Exit status 1
22 error Failed at the angular-seed@0.0.0 preprotractor script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

```

I guess there is some issue with webdriver.

I am using windows 8.1 Pro, Node 14.15.0 and NPM 6.14.8

**Comment by PraneetDixit** [comment]
Update - The issue is solved now. I made some changes to make things work - 

```
npm i -g protractor
cd path\to\node_modules\protractor
npm i webdriver-manager
webdriver-manager update
```

I guess there was some issue with version of protractor. I am closing this issue as my problem is solved.
